WebSiteProject/Controllers/F_ThingsToDoController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Services.Interface;
using Services.Manager;
using SQLModel;
using SQLModel.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using WebSiteProject.Code;
using ViewModels;
using WebSiteProject.Models.F_ViewModels;


namespace WebSiteProject.Controllers
{
    public class F_ThingsToDoController : AppController
    {
        MasterPageManager _IMasterPageManager;
        ILangManager _ILangManager;
        ISiteLayoutManager _ISiteLayoutManager;
        ILoginManager _ILoginManager;
        IMenuManager _IMenuManager;
        IModelLinkManager _IModelLinkManager;
        ADRightDownManager _ADRightDownManager;

        WebSiteProject.Models.ForestEntities db = new Models.ForestEntities();

        public F_ThingsToDoController()
        {
            _IMasterPageManager = new MasterPageManager(connectionstr, LangID, Common.GetLangDict());
            _ISiteLayoutManager = serviceinstance.SiteLayoutManager;
            _ILangManager = serviceinstance.LangManager;
            _ILoginManager = serviceinstance.LoginManager;
            _IMenuManager = serviceinstance.MenuManager;
            _IModelLinkManager = serviceinstance.ModelLinkManager;
            _ADRightDownManager = new ADRightDownManager(new SQLRepository<ADRightDown>(connectionstr));
        }

        // GET: F_ThingsToDo
        public ActionResult Index(int? langid)
        {
            var site_id = 4; //這是ThingsToDo的輪播ID
            if (Session["LangID"] == null)
            {
                var DefaultLang = System.Web.Configuration.WebConfigurationManager.AppSettings["DefaultLang"];
                _ILangManager = serviceinstance.LangManager;
                var alllang = _ILangManager.GetAll();
                if (alllang != null)
                {
                    if (alllang.Any(v => v.Lang_Name == DefaultLang))
                    {
                        langid = alllang.Where(v => v.Lang_Name == DefaultLang).First().ID.Value;
                    }
                }
                Session["LangID"] = langid.ToString();
                Session.Timeout = 600;
            }
            else
            {
                if (langid == null)
                {
                    int _langid = 1;
                    if (int.TryParse(Session["LangID"].ToString(), out _langid) == false)
                    {
                        langid = 1;
                    }
                    else { langid = _langid; }
                }
                else
                {
                    Session["LangID"] = langid.ToString();
                }
            }

            HomeViewModel viewmodel = new HomeViewModel();
            //讀取logo圖片
            _IMasterPageManager.SetModel<HomeViewModel>(ref viewmodel, "P", langid.ToString(), "");
            viewmodel.SEOScript = _IMasterPageManager.GetSEOData("", "", langid.ToString());
            viewmodel.ADMain = _IMasterPageManager.GetADMain("P", langid.ToString(), site_id);
            viewmodel.ADMobile = _IMasterPageManager.GetADMain("M", langid.ToString(), site_id);
            viewmodel.TrainingSiteData = _ISiteLayoutManager.GetTrainingSiteData(Common.GetLangText("另開新視窗")).AntiXss(new string[] { "class" });

            var sitemenu = _ISiteLayoutManager.PagingMain(new ViewModels.SearchModelBase()
            {
                Limit = 100,
                Key = Device,
                NowPage = 1,
                Offset = 0,
                Sort = "ID",
                LangId = langid.ToString()
            });
            if (sitemenu.total > 0)
            {
                var layoutpagelist = ((List<PageLayout>)sitemenu.rows);
                if (layoutpagelist.Any(v => v.Title == "焦點新聞"))
                {
                    viewmodel.PageLayoutModel1 = _IMasterPageManager.GetSiteLayout(sitemenu.rows, "焦點新聞", langid.ToString()).First();
                }
                else { viewmodel.PageLayoutModel1 = new HomePageLayoutModel(); }
                if (layoutpagelist.Any(v => v.Title == "活動專區"))
                {
                    viewmodel.PageLayoutModel2 = _IMasterPageManager.GetSiteLayout(sitemenu.rows, "活動專區", langid.ToString()).First();
                }
                else { viewmodel.PageLayoutModel2 = new HomePageLayoutModel(); }
            }
            else
            {
                viewmodel.PageLayoutModel1 = new HomePageLayoutModel();
                viewmodel.PageLayoutModel2 = new HomePageLayoutModel();
                ViewBag.sitemenu = new List<PageLayout>();
                ViewBag.sitemenupart = "";
            }
            viewmodel.BannerImage = "";
            viewmodel.PageLayoutOP1 = _ISiteLayoutManager.GetPageLayoutOP1Edit(langid.ToString());
            viewmodel.PageLayoutOP2 = _ISiteLayoutManager.GetPageLayoutOP2Edit(langid.ToString());
            viewmodel.PageLayoutOP3 = _ISiteLayoutManager.GetPageLayoutOP3Edit(langid.ToString());
            viewmodel.PageLayoutActivityModel = _ISiteLayoutManager.PageLayoutActivity(langid.ToString());

            viewmodel.LinkItems = _IModelLinkManager.PagingItem("Y", new SearchModelBase()
            {
                LangId = this.LangID,
                Limit = -1,
                Sort = "Sort"
            }).rows;


            viewmodel.Title = "Things to do";
            //標題和內容
            ViewBag.Title = Server.HtmlDecode(db.F_Thingtodo_Index.FirstOrDefault().F_Thingtodo_Index_Title);
            ViewBag.Content = Server.HtmlDecode(db.F_Thingtodo_Index.FirstOrDefault().F_Thingtodo_Index_Content);

            //五大標題+圖
            ViewBag.F_Thingtodo_Type = db.F_Thingtodo_Type.ToList();



            return View(viewmodel);
        }


        #region ThingToDo_List
        public ActionResult ThinngsToDo_List(int? langid, int F_TTD_Id)
        {
            var site_id = 5; //這是ThingsToDo的輪播ID
            var mode_id = 9; //這是ThingsToDo的ModeID
            var list_id = 1; //這是ThingsToDo的訊息列表ID

            switch (F_TTD_Id)
            {
                case 1:
                    site_id = 5; //這是ThingsToDo的輪播ID
                    list_id = 1; //這是ThingsToDo的訊息列表ID

                    break;
                case 2:
                    site_id = 6; //這是ThingsToDo的輪播ID
                    list_id = 2; //這是ThingsToDo的訊息列表ID

                    break;
                case 3:
                    site_id = 7; //這是ThingsToDo的輪播ID
                    list_id = 3; //這是ThingsToDo的訊息列表ID

                    break;
                case 4:
                    site_id = 8; //這是ThingsToDo的輪播ID
                    list_id = 4; //這是ThingsToDo的訊息列表ID
                    break;
                case 5:
                    site_id = 9; //這是ThingsToDo的輪播ID
                    list_id = 5; //這是ThingsToDo的訊息列表ID

                    break;
            }            

            if (Session["LangID"] == null)
            {
                var DefaultLang = System.Web.Configuration.WebConfigurationManager.AppSettings["DefaultLang"];
                _ILangManager = serviceinstance.LangManager;
                var alllang = _ILangManager.GetAll();
                if (alllang != null)
                {
                    if (alllang.Any(v => v.Lang_Name == DefaultLang))
                    {
                        langid = alllang.Where(v => v.Lang_Name == DefaultLang).First().ID.Value;
                    }
                }
                Session["LangID"] = langid.ToString();
                Session.Timeout = 600;
            }
            else
            {
                if (langid == null)
                {
                    int _langid = 1;
                    if (int.TryParse(Session["LangID"].ToString(), out _langid) == false)
                    {
                        langid = 1;
                    }
                    else { langid = _langid; }
                }
                else
                {
                    Session["LangID"] = langid.ToString();
                }
            }

            HomeViewModel viewmodel = new HomeViewModel();
            //讀取logo圖片
            _IMasterPageManager.SetModel<HomeViewModel>(ref viewmodel, "P", langid.ToString(), "");
            viewmodel.SEOScript = _IMasterPageManager.GetSEOData("", "", langid.ToString());
            viewmodel.ADMain = _IMasterPageManager.GetADMain("P", langid.ToString(), site_id);
            viewmodel.ADMobile = _IMasterPageManager.GetADMain("M", langid.ToString(), site_id);
            viewmodel.TrainingSiteData = _ISiteLayoutManager.GetTrainingSiteData(Common.GetLangText("另開新視窗")).AntiXss(new string[] { "class" });

            var sitemenu = _ISiteLayoutManager.PagingMain(new ViewModels.SearchModelBase()
            {
                Limit = 100,
                Key = Device,
                NowPage = 1,
                Offset = 0,
                Sort = "ID",
                LangId = langid.ToString()
            });
            if (sitemenu.total > 0)
            {
                var layoutpagelist = ((List<PageLayout>)sitemenu.rows);
                if (layoutpagelist.Any(v => v.Title == "焦點新聞"))
                {
                    viewmodel.PageLayoutModel1 = _IMasterPageManager.GetSiteLayout(sitemenu.rows, "焦點新聞", langid.ToString()).First();
                }
                else { viewmodel.PageLayoutModel1 = new HomePageLayoutModel(); }
                if (layoutpagelist.Any(v => v.Title == "活動專區"))
                {
                    viewmodel.PageLayoutModel2 = _IMasterPageManager.GetSiteLayout(sitemenu.rows, "活動專區", langid.ToString()).First();
                }
                else { viewmodel.PageLayoutModel2 = new HomePageLayoutModel(); }
            }
            else
            {
                viewmodel.PageLayoutModel1 = new HomePageLayoutModel();
                viewmodel.PageLayoutModel2 = new HomePageLayoutModel();

WebSiteProject/Views/F_ThingsToDo/Article.cshtml
 <!--banner start-->
@{
    Layout = WebSiteProject.Code.Common.GetIndexLayout(Model.LangId);
}

@model HomeViewModel


<style>
    .F_img_center{
        margin:0px auto;
    }
</style>


@{
    var TTDModel = (WebSiteProject.Models.MessageItem)ViewBag.TTD_Detail;
    var banner = ViewBag.MessageBanner;
    var dat = (DateTime)TTDModel.PublicshDate;
    <!--banner start-->
<div class="page_banner one_pic">
    <!--一張封面照；建議尺寸寬2000*600px；後台無上傳圖片時，img不顯示(但div page_banner要保留)；圖片alt=標題-->
    @if (@banner == "" || banner == null)
    {

    }
    else
    {
        <img src="@Url.Content("~/UploadImage/MessageItem/")@banner" alt="@TTDModel.Title" />
    }
    </div>
    <!--banner end-->
    <!--page_content start-->
    <div class="page_content">

        <!--page top start-->
        <div class="page_top">
            <div class="container">
                <div class="col-md-7 col-sm-6 col-xs-12 page_top_left">
                    <a href="#;return false;" title="Content area" accesskey="C" id="main-content">:::</a> &nbsp;
                    <a href="@Url.Action("Index","Home")" title="Home"><i class="fas fa-home" aria-hidden="true"></i><span class="sr-only">Home</span></a><i class="fa fa-angle-right" aria-hidden="true"></i>
                    <a href="@Url.Action("Index","F_ThingsToDo",new { mid = 24})" title="Things to do">Things to do</a><i class="fa fa-angle-right" aria-hidden="true"></i>
                    <a href="javascript:history.back()" title="@ViewBag.Category">@ViewBag.Category</a><i class="fa fa-angle-right" aria-hidden="true"></i>@TTDModel.Title
                </div>
                <div class="col-md-5 col-sm-6 col-xs-12">
                    <div class="page_top_right">
                        @{
                            WebSiteProject.Models.F_ViewModels.UnitPrint unit = ViewBag.Unit;
                        }
                        @{

                            if (unit.isForward)
                            {
                                <a href="#" @*target="_blank"="*@ onclick="window.open('@Url.Action("Forward","F_Recommendedtrips" ,new {Title=TTDModel.Title,Url=Request.Url.ToString() })', 'forward', config='height=750,width=650')" title="forward(new window)"><img src="@Url.Content("~/img/icon_mail.png")" alt="mail"></a>
                            }
                            if (unit.isPrint)
                            {
                                <a href="@Url.Action("Print","Message",new { mid=24,id =TTDModel.ItemID})" target="_blank" title="print(new window)"><img src="@Url.Content("~/img/icon_print.png")" alt="print"></a>
                            }
                            <!--<a href="#" target="_blank" title="link - web name(new window)"><img src="img/icon_link.png" alt=""></a>
        <a href="#" target="_blank" title="download - file name(new window)"><img src="img/icon_download.png" alt=""></a>-->
                            if (unit.isShare)
                            {
                                <a href="http://www.facebook.com/share.php?u=@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))" target="_blank" title="facebook share(new window)"><img src="@Url.Content("~/img/icon_facebook.png")" alt="facebook"></a>
                                <a href="https://twitter.com/share?text=@ViewBag.Title&url=@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))" target="_blank" title="twitter share(new window)"><img src="@Url.Content("~/img/icon_twitter.png")" alt="twitter"></a>
                                <a href="http://plurk.com/?qualifier=shares&status=[分享]@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))" target="_blank" title="plurk share(new window)"><img src="@Url.Content("~/img/icon_plurk.png")" alt="plurk"></a>
                                <a href="http://line.naver.jp/R/msg/text/?@TTDModel.Title%0D%0A@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))" target="_blank" title="line share(new window)"><img src="@Url.Content("~/img/icon_line.png")" alt="line"></a>
                            }
                            if (unit.isRSS)
                            {

                            }
                        }


                        @*<a href="forward.html" target="_blank" title="forward(new window)"><img src="~/img/icon_mail.png" alt=""></a>
                        <a href="@Url.Action("Print","Message",new { mid=179,id=TTDModel.ItemID})" target="_blank" title="print(new window)"><img src="~/img/icon_print.png" alt="print"></a>
                        <a href="#" target="_blank" title="link - web name(new window)"><img src="img/icon_link.png" alt=""></a>
    <a href="#" target="_blank" title="download - file name(new window)"><img src="img/icon_download.png" alt=""></a>
                        <a href="http://www.facebook.com/share.php?u=@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))" target="_blank" title="facebook share(new window)"><img src="~/img/icon_facebook.png" alt=""></a>
                        <a href="https://twitter.com/share?text=@TTDModel.Title&url=@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))" target="_blank" title="twitter share(new window)"><img src="~/img/icon_twitter.png" alt=""></a>
                        <a href="http://plurk.com/?qualifier=shares&status=[分享]@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))(@TTDModel.Title&url)" target="_blank" title="plurk share(new window)"><img src="~/img/icon_plurk.png" alt=""></a>*@
                    </div>
                </div>
            </div>
        </div>
        <!--page top end-->
        <!--page_con start-->
        <div class="page_con">
            <div class="container">

                <h2>@TTDModel.Title</h2>

                <div class="date">@dat.ToString("yyyy/MM/dd")</div>

                <div class="edit_con">
                    <!--文繞圖 start-->
                    @if (string.IsNullOrEmpty(@TTDModel.ImageFileOrgName) == false)
                    {
                        <!--圖片置左-->
                        if (@TTDModel.ImageFileLocation == "1")
                        {
                            <img src="@Url.Content("~/UploadImage/MessageItem/")@TTDModel.ImageFileName" class="img_padding" alt="@TTDModel.ImageFileDesc" title="@TTDModel.ImageFileDesc" align="left">
                        }
                        else if (@TTDModel.ImageFileLocation == "2")
                        {
                            <div align="center"><p class="text_center"><img src="@Url.Content("~/UploadImage/MessageItem/")@TTDModel.ImageFileName" class="img_padding" title="@TTDModel.ImageFileDesc" alt="@TTDModel.ImageFileOrgName"></p></div>
                        }
                        else if (@TTDModel.ImageFileLocation == "3")
                        {
                            <img src="@Url.Content("~/UploadImage/MessageItem/")@TTDModel.ImageFileName" class="img_padding" alt="@TTDModel.ImageFileDesc" title="@TTDModel.ImageFileDesc" align="right">
                        }

                    }

                    <!--文繞圖 end-->
                    
                    @Html.Raw(HttpUtility.HtmlDecode(TTDModel.HtmlContent/*.safeHtmlFragment*/))


                </div>

                <!--相關連結+檔案下載 start-->
                <div class="page_bottom">

                @{
                    if (TTDModel.LinkUrl != null && TTDModel.LinkUrl != "")
                    {
                        <div class="link">
                            <div class="title"><i class="fa fa-link" aria-hidden="true"></i>Link</div>
                            <div class="con_font">
                                <a href="@TTDModel.LinkUrl" target="_blank" title="@TTDModel.LinkUrlDesc (new window)">@TTDModel.LinkUrlDesc</a>
                            </div>
                        </div>
                    }

                    if (TTDModel.UploadFileName != null && TTDModel.UploadFileName != "")
                    {
                        <div class="download">
                            <div class="title"><i class="fa fa-download" aria-hidden="true"></i>Download</div>
                            <div class="con_font">
                                <a href="@Url.Action("FileDownLoad","Message")?itemid=@TTDModel.ItemID" target="_blank" title="@TTDModel.UploadFileDesc (new window)">@TTDModel.UploadFileName</a>
                            </div>
                        </div>
                    }

                }
                    
                   
                </div>                <!--相關連結+檔案下載 end-->

                <div class="back_btn">
                    <a href="javascript:history.back()" title="Back"><span class="btn_01">Back</span></a>
                </div>
            </div>
        </div>
        <!--page_con end-->

    </div>
    <!--page_content end-->
    <!--breadcrumbs start-->
    <div class="breadcrumbs">
        <div class="container">
            <div class="title">You are here</div>
            <div class="font"><a href="@Url.Action("Index", "Home")" title="Home"> Home</a> / <a href="@Url.Action("Index","F_ThingsToDo",new { mid = 24})" title="Things to do">Things to do</a> / <a href="javascript:history.back()" title="@ViewBag.Category">@ViewBag.Category</a> / @TTDModel.Title</div>
        </div>
    </div>
    <!--breadcrumbs end-->

}



<script>
    $(document).ready(function () {
        $("img").parent("p").addClass("text-center");
        $("#mainNav>li:nth-child(2)").children().addClass("active").parent().siblings().children().removeClass("active");


    });
</script>

WebSiteProject/Views/F_ThingsToDo/ThingToDo_Detail.cshtml
 <!--banner start-->
@{
    Layout = WebSiteProject.Code.Common.GetIndexLayout(Model.LangId);
}

@model HomeViewModel


<style>
    .F_img_center{
        margin:0px auto;
    }
</style>


@{
    var TTDModel = (WebSiteProject.Models.MessageItem)ViewBag.TTD_Detail;

    <!--banner start-->
    <div class="page_banner one_pic">
        <!--一張封面照；建議尺寸寬2000*600px；後台無上傳圖片時，img不顯示(但div page_banner要保留)；圖片alt=標題-->
        <img src="@Url.Content("~/UploadImage/MessageItem/")@TTDModel.ImageFileName" alt="@TTDModel.Title" />
    </div>
    <!--banner end-->
    <!--page_content start-->
    <div class="page_content">

        <!--page top start-->
        <div class="page_top">
            <div class="container">
                <div class="col-md-7 col-sm-6 col-xs-12 page_top_left">
                    <a href="#;return false;" title="Content area" accesskey="C" id="main-content">:::</a> &nbsp;
                    <a href="@Url.Action("Index","Home")" title="Home"><i class="fas fa-home" aria-hidden="true"></i></a><span class="sr-only">Home</span><i class="fa fa-angle-right" aria-hidden="true"></i>
                    <a href="@Url.Action("Index","F_ThingsToDo",new { mid = 24})" title="Things to do">Things to do</a><i class="fa fa-angle-right" aria-hidden="true"></i>
                    <a href="javascript:history.back()" title="@ViewBag.Category">@ViewBag.Category</a><i class="fa fa-angle-right" aria-hidden="true"></i>@TTDModel.Title
                </div>
                <div class="col-md-5 col-sm-6 col-xs-12">
                    <div class="page_top_right">
                        <a href="forward.html" target="_blank" title="forward(new windown)"><img src="~/img/icon_mail.png" alt=""></a>
                        <a href="@Url.Action("Print","Message",new { mid=179,id=TTDModel.ItemID})" target="_blank" title="print(new windown)"><img src="~/img/icon_print.png" alt="print"></a>
                        <!--<a href="#" target="_blank" title="link - web name(new window)"><img src="img/icon_link.png" alt=""></a>
        <a href="#" target="_blank" title="download - file name(new window)"><img src="img/icon_download.png" alt=""></a>-->
                        <a href="http://www.facebook.com/share.php?u=@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))" target="_blank" title="facebook share(new window)"><img src="~/img/icon_facebook.png" alt=""></a>
                        <a href="https://twitter.com/share?text=@TTDModel.Title&url=@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))" target="_blank" title="twitter share(new window)"><img src="~/img/icon_twitter.png" alt=""></a>
                            <a href="http://plurk.com/?qualifier=shares&status=[分享]@(HttpUtility.UrlEncode(Request.Url.AbsoluteUri))(@TTDModel.Title&url)" target="_blank" title="plurk share(new window)"><img src="~/img/icon_plurk.png" alt=""></a>
</div>
                </div>
            </div>
        </div>
        <!--page top end-->
        <!--page_con start-->
        <div class="page_con">
            <div class="container">

                <h2>@TTDModel.Title</h2>

                <div class="date">@TTDModel.PublicshDate</div>

                <div >
                    <!--由後台編輯器編輯-->
                    <!--文繞圖 start-->
                    <!--<img src="img/pic_01.jpg" class="img_padding" alt="" align="left">置左
                    <img src="img/pic_01.jpg" class="img_padding" alt="" align="right">置右-->
                    @*<div align="center">
                        <img src="img/t_pic_05.jpg" class="img_padding" alt="image Description">
                    </div>*@
                    <!--文繞圖 end-->
                    @*Having walked for hours without seeing a soul, it almost came as a surprise when we spotted a couple heading towards us from across the Rhine Valley.<br /><br />
                    “It’s so nice to see young international tourists enjoying our country!” exclaimed a local man, who, along with his wife, couldn’t contain his genuine excitement at seeing visitors exploring their homeland.<br /><br />
                    Tourists often receive a mixed reception abroad, but not here. Not in the least-visited country in Europe. Welcome to Liechtenstein.<br /><br />
                    <div class="text-center">
                        <img src="img/r_pic_02.jpg" class="img_padding" alt="image Description">
                    </div>
                    <div class="w-800">
                        <div class="title_01">300 years of Liechtenstein</div>
                        My friends and I had just set off on the newly-created Liechtenstein Trail – a 75km walking route which runs the entire length of the country, from its northeastern border with Austria, down to the far southwest, where the valley bends into Switzerland. It was launched to celebrate the 300th anniversary of Liechtenstein’s independence and can be completed in either direction.<br /><br />
                        We chose to go from top to bottom as our return flight was from Zurich, and the Swiss city is easily reached from Sargans, near the southern end of Liechtenstein.<br /><br />
                    </div>*@
                    @Html.Raw(TTDModel.HtmlContent)


                </div>

                <!--相關連結+檔案下載 start-->
                <div class="page_bottom">

                @{
                    if (TTDModel.LinkUrl != null && TTDModel.LinkUrl != "")
                    {
                        <div class="link">
                            <div class="title"><i class="fa fa-link" aria-hidden="true"></i>Link</div>
                            <div class="con_font">
                                <a href="@TTDModel.LinkUrl" target="_blank" title="@TTDModel.LinkUrlDesc (new window)">@TTDModel.LinkUrlDesc</a>
                            </div>
                        </div>
                    }

                    if (TTDModel.UploadFileName != null && TTDModel.UploadFileName != "")
                    {
                        <div class="download">
                            <div class="title"><i class="fa fa-download" aria-hidden="true"></i>Download</div>
                            <div class="con_font">
                                <a href="@Url.Action("FileDownLoad","Message")?itemid=@TTDModel.ItemID" target="_blank" title="@TTDModel.UploadFileDesc (new window)">@TTDModel.UploadFileName</a>
                            </div>
                        </div>
                    }

                }
                    
                   
                </div>                <!--相關連結+檔案下載 end-->

                <div class="back_btn">
                    <a href="javascript:history.back()" title="Back"><span class="btn_01">Back</span></a>
                </div>
            </div>
        </div>
        <!--page_con end-->

    </div>
    <!--page_content end-->
    <!--breadcrumbs start-->
    <div class="breadcrumbs">
        <div class="container">
            <div class="title">You are here</div>
            <div class="font"><a href="index.html" title="Home">Home</a> / <a href="things.html" title="Things to do">Things to do</a> / <a href="things_detail_03.html" title="@ViewBag.Category">@ViewBag.Category</a> / @TTDModel.Title</div>
        </div>
    </div>
    <!--breadcrumbs end-->

}



<script>
    $(document).ready(function () {
        $("img").parent("p").addClass("text-center");



    });
</script>