WebSiteProject/Models/Destination_Index.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination_Index
    {
        public int Destination_ID { get; set; }
        public string Destination_Title { get; set; }
        public string Destination_Context { get; set; }
    }
}

WebSiteProject/Areas/webadmin/Controllers/ADController.cs
using Services.Interface;
using Services.Manager;
using SQLModel;
using SQLModel.Models;
using System;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using WebSiteProject.Code;
using Utilities;
using ViewModels;
using System.Configuration;
using System.IO;

namespace WebSiteProject.Areas.webadmin.Controllers
{
    [Authorize]
    public class ADController : AppController
    {
        WebSiteProject.Models.ForestEntities db = new Models.ForestEntities();

        IADManager _IADManager;
        readonly SQLRepository<Img> _imgsqlrepository;
        public ADController()
        {
            _imgsqlrepository = new SQLRepository<Img>(connectionstr);
        }

        #region ADEdit
        [AuthoridUrl("AD/Index", "type,stype")]
        public ActionResult ADEdit(string type,string id,string stype,int siteid=1,int maintype=-1)
        {
            
            //20191230_Forest客製化
            #region 20191230_Forest客製化
            //var SiteList = db.SiteLists.Select(s => new { ID = s.SiteList_ID, Name = s.SiteList_Name_ch + "－" + s.SiteList_Name_en, s.Sort }).OrderBy(s => s.Sort);
            //ViewBag.SiteList = new SelectList(SiteList, "ID", "Name");
            #endregion



            if (string.IsNullOrEmpty(stype)) { stype = "P"; }
            if (type != null) { Session["ADType"] = type; }
            else
            {
                if (Session["ADType"] != null) { type = Session["ADType"].ToString(); }
            }
            if (type == null) { return RedirectToAction("Index", "Home"); }
            CheckAuth(System.Reflection.MethodBase.GetCurrentMethod());
            var model = new ADEditModel();
          
            var imageadpath = "";
            var pathstr = "";
            var prestr = stype == "M" ? "手機板-" : "";
            var prestr2 = stype == "M" ? "Phome-" : "";
            if (type == "right")
            {
                _IADManager = new ADRightManager(new SQLRepository<ADRight>(connectionstr));       
                ViewBag.Title = "輪播廣告管理("+ prestr+"快速選單)";
                imageadpath = "ad_right";
                pathstr = "ADRight";
            }
            else if (type == "rightdown")
            {
                _IADManager = new ADRightDownManager(new SQLRepository<ADRightDown>(connectionstr));
                ViewBag.Title = "輪播廣告管理("+ prestr+"書籍專區)";
                imageadpath = "ad_rightdown";
                pathstr = "ADRightDown";
            }
            else if (type == "main")
            {
                _IADManager = new ADMainManager(new SQLRepository<ADMain>(connectionstr));
                
                if (maintype==176)
                {
                    ViewBag.Title = "RecommendTrip_Banner(" + prestr2 + "Master)";
                }
                else if(maintype == 45)
                {
                    ViewBag.Title = "Fact_Banner(" + prestr2 + "Master)";
                }
                else
                {
                    ViewBag.Title = "輪播廣告管理(" + prestr + "主廣告)";
                }
                imageadpath = "ad_main";
                pathstr = "ADMain";
            }
            else if (type == "down")
            {
                _IADManager = new ADDownManager(new SQLRepository<ADDown>(connectionstr));
                ViewBag.Title = "輪播廣告管理("+ prestr+"友會連結)";
                imageadpath = "ad_down";
                pathstr = "ADDown";
            }
            else if (type == "center")
            {
                _IADManager = new ADCenterManager(new SQLRepository<ADCenter>(connectionstr));
                ViewBag.Title = "輪播廣告管理("+ prestr+"橫幅廣告)";
                imageadpath = "ad_center";
                pathstr = "ADCenter";
            }
            else if (type == "mobile")
            {
                _IADManager = new ADMobileManager(new SQLRepository<ADMobile>(connectionstr));
                ViewBag.Title = "輪播廣告管理(手機版)";
                imageadpath = "ad_mobile";
                pathstr = "ADMobile";
            }
            else if (type == "mobileblock")
            {
                _IADManager = new ADMobileBlockManager(new SQLRepository<ADMobileBlock>(connectionstr));
                ViewBag.Title = "輪播廣告管理(手機版-各區塊)";
                imageadpath = "ad_mobileblock";
                pathstr = "ADMobileBlock";
            }
            else if (siteid == 17)
            {
                _IADManager = new ADMainManager(new SQLRepository<ADMain>(connectionstr));
                ViewBag.Title = "RecommendTrip_Article_Banner(" + prestr2 + "Master)";
                imageadpath = "ad_main";
                pathstr = "ADMain";
                model.Site_ID = siteid;
            }
            if (id.IsNullorEmpty()) {
                var imgdata = _imgsqlrepository.GetByWhere("item=@1", new object[] { imageadpath });
                if (imgdata.Count() > 0) {
                    model.AD_Height = imgdata.First().height;
                    model.AD_Width = imgdata.First().width;
                }
                ViewBag.mantype = maintype;
                ViewBag.siteid = siteid;
                model.Site_ID = siteid;
                return View(model);
            }
            model = _IADManager.GetModel(id);
            model.ImageUrl = Url.Content("~/UploadImage/"+ pathstr +"/" + model.Img_Name_Thumb);
            model.Type = type;
            model.SType = stype;
            model.Site_ID = siteid;
            ViewBag.mantype = maintype;
            ViewBag.siteid = siteid;
            return View(model);
        }
        #endregion


        #region Index
        [AuthoridUrl("AD/Index", "type,stype")]
        public ActionResult Index(string type,string stype, int? site_id, int MenuType=0 )
        {
            //20191230_Forest客製化__Start
            #region 20191230_Forest客製化

            var siteid = site_id ?? TempData["site_id"] ?? 1;
            if (TempData["site_id"] == null)
            {
                TempData["site_id"] = siteid;
            }
            
            ViewBag.sitid = -1;
            var SiteList = db.SiteLists.Select(s => new { ID = s.SiteList_ID, Name = s.SiteList_Name_ch + "－" + s.SiteList_Name_en, s.Sort }).OrderBy(s => s.Sort);            
            ViewBag.SiteList = new SelectList(SiteList, "ID", "Name", siteid);
            if(site_id!=null)
            {
                ViewBag.SiteTile = db.SiteLists.Where(p => p.SiteList_ID == site_id).FirstOrDefault().SiteList_Name_en;
                ViewBag.sitid = siteid;
                if(site_id == 17)
                {
                    var id = Int32.Parse(type);
                   ViewBag.RecommendedTrips_Title = db.RecommendedTrips.Where(p => p.RecommendedTrips_ID == id).FirstOrDefault().RecommendedTrips_Title;
                }
            }
            Session["F_MenuType"] = MenuType==0? 0: MenuType;
            ViewBag.MenuType = MenuType == 0 ? 0 : Session["F_MenuType"];

            #endregion
            //20191230_Forest客製化__End




            if (this.IsAuthenticated)
            {
                if (string.IsNullOrEmpty(stype)) { stype = "P"; }
                if (type != null) { Session["ADType"] = type; }
                else
                {
                    if (Session["ADType"] != null) { type = Session["ADType"].ToString(); }
                }
                if (type == null) { return RedirectToAction("Index", "Home"); }
                type = type.AntiXssEncode();
                stype = stype.AntiXssEncode();
                CheckAuth(System.Reflection.MethodBase.GetCurrentMethod());
                ViewBag.Type = type.AntiXssEncode();
                ViewBag.stype = stype.AntiXssEncode();
                if (type == "right")
                {
                    _IADManager = new ADRightManager(new SQLRepository<ADRight>(connectionstr));
                    ViewBag.Title = "輪播廣告管理(快速選單)";
                    if (stype == "M") { ViewBag.Title = "手機板輪播廣告管理(手機版-快速選單)"; }
                }
                else if (type == "rightdown")
                {
                    _IADManager = new ADRightDownManager(new SQLRepository<ADRightDown>(connectionstr));
                    ViewBag.Title = "輪播廣告管理(書籍專區)";
                    if (stype == "M") { ViewBag.Title = "輪播廣告管理(手機版-書籍專區)"; }
                }
                else if (type == "main")
                {
                    _IADManager = new ADMainManager(new SQLRepository<ADMain>(connectionstr));
                    ViewBag.Title = "輪播廣告管理(主廣告)";
                    if (stype == "M") { ViewBag.Title = "輪播廣告管理(手機版-主廣告)"; }
                  
                    ViewBag.ReTitle = "RecommendTrip_Banner(Master)";
                    if (stype == "M") { ViewBag.ReTitle = "RecommendTrip_Banner(Phone-Master)"; }
                    if (MenuType == 45)
                    {
                        ViewBag.ReTitle = "Fact_Banner(Master)";
                    }
                    ViewBag.siteid = siteid;
                }
                else if (type == "down")
                {
                    _IADManager = new ADDownManager(new SQLRepository<ADDown>(connectionstr));
                    ViewBag.Title = "輪播廣告管理(友會連結)";
                    if (stype == "M") { ViewBag.Title = "輪播廣告管理(手機版-友會連結)"; }
                }
                else if (type == "center")
                {
                    _IADManager = new ADCenterManager(new SQLRepository<ADCenter>(connectionstr));
                    ViewBag.Title = "輪播廣告管理(橫幅廣告)";
                    if (stype == "M") { ViewBag.Title = "輪播廣告管理(手機版-橫幅廣告)"; }
                }
                else if (type == "mobile")
                {
                    _IADManager = new ADMobileManager(new SQLRepository<ADMobile>(connectionstr));
                    ViewBag.Title = "輪播廣告管理(手機版)";
                }
                else if (type == "mobileblock")
                {

WebSiteProject/Areas/webadmin/Views/Destination_Index/AD.cshtml
@{
    if (TempData["Msg"] != null)
    {
        <script>
            $(function () {
                var Msg = @Html.Raw(Json.Encode(TempData["Msg"]));
                alert(Msg);
            });
        </script>
    }
}




<form class="form-horizontal form-bordered" method="Post" id="editform" action="/forest/webadmin/AD/Save" enctype="multipart/form-data">
    <input data-val="true" data-val-number="欄位 ID 必須是數字。" data-val-required="ID 欄位是必要項。" id="ID" name="ID" type="hidden" value="-1">
    <input id="Type" name="Type" type="hidden" value="main">
    <input id="Img_Name_Ori" name="Img_Name_Ori" type="hidden" value="">
    <input id="Img_Name_Thumb" name="Img_Name_Thumb" type="hidden" value="">
    <input id="UploadVideoFileName" name="UploadVideoFileName" type="hidden" value="">
    <input id="UploadVideoFilePath" name="UploadVideoFilePath" type="hidden" value="">
    <input id="SType" name="SType" type="hidden" value="P">
    <input id="hid_isAdd" type="hidden" name="isAdd">
    <div class="portlet light form-fit bordered">
        <div class="portlet-body form">
            <div class="form-horizontal form-bordered">
                <div class="form-body" id="form-body">
                    <div class="form-group">
                        <div class="col-md-2 col-sm-2 col-xs-12 bg-grey_1 search_item">目的地</div>
                        <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                            @Html.TextBoxFor(model => model.Destination_Type_ID, new { @Value = @DESid, style = "display:none" })
                            @*<input type="hidden" name="DFTR.Destination_Type_ID" value="@DESid"/>*@
                            <label>@DESName</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-2 col-sm-2 col-xs-12 bg-grey_1 search_item">顯示日期</div>
                        <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                            <div class="input-group input-large" style="float:left">
                                <div class="date-picker input-daterange" data-date-format="yyyy/mm/dd">
                                    <input class="form-control text-box single-line" id="StDateStr" name="StDateStr" placeholder="開始日期" type="text" value="">
                                </div>
                                <span class="input-group-addon"> to </span>
                                <div class="date-picker input-daterange" data-date-format="yyyy/mm/dd">
                                    <input class="form-control text-box single-line" id="EdDateStr" name="EdDateStr" placeholder="結束日期" type="text" value="">
                                </div>

                            </div>
                            <div class="" style="float:left">
                                <button type="button" class="btn blue" id="btn_clear">清空</button>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-2 col-sm-2 col-xs-12 search_item"><span class="red">*</span>廣告名稱</div>
                        <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                            <input class="form-control checkitem text-box single-line" id="AD_Name" name="AD_Name" type="text" value="">
                            <span class="required" id="AD_Name-error" style="display:none">廣告名稱必須輸入</span>
                        </div>
                    </div>
                    <div class="form-group" id="F_Description">
                        <div class="col-md-2 col-sm-2 col-xs-12 search_item">廣告描述</div>
                        <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                            <textarea cols="80" id="ADDesc" rows="3" class="form-control" maxlength="500"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-2 col-sm-2 col-xs-12 search_item">廣告圖片上傳</div>
                        <div class="col-md-10 col-sm-4 col-xs-12 bg-white mobile_white">

                            <div id="div_oldfile" style="display:none"><a target="preview"></a><label style="color:blue;margin-left:10px;cursor:pointer" id="delimage">刪除</label></div>
                            <input id="file_image" type="file" name="uploadfile" accept="image/*">
                            <span style="color:red;padding-left; font-size:12px">檔案類型jpg、png、gif，建議檔案大小2MB內，建議尺寸1200*2000px</span>
                        </div>
                    </div>
                    <div class="form-group" id="F_Video">
                        <div class="col-md-2 col-sm-12 search_item">影片上傳</div>
                        <div class="col-md-10 col-sm-12 bg-white mobile_white">
                            <div class="col-md-12">
                                <div id="div_olduploadfile" style="display:none"><a href="/forest/webadmin/AD/VideoDownLoad/-1" target="preview"></a><label style="color:blue;margin-left:10px;cursor:pointer" id="delupfile">刪除</label></div>
                                <div id="div_nofile" style="display:inline">
                                    <div class="col-md-10">
                                        <input type="file" id="uploadvideofile" class="display_inline" name="UploadVideoFile" accept="video/*">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-2 col-sm-2 col-xs-12 search_item">連結路徑</div>
                        <div class="col-md-10 col-sm-4 col-xs-12 bg-white mobile_white">
                            <input class="form-control text-box single-line" id="Link_Href" name="Link_Href" type="text" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-2 col-sm-2 col-xs-12 search_item">開啟方式</div>
                        <div class="col-md-10  col-xs-12 bg-white mobile_white">
                            <input checked="checked" id="Link_Mode" name="Link_Mode" style="margin-left :0px" type="radio" value="1">原視窗
                            <input id="Link_Mode" name="Link_Mode" style="margin-left :40px" type="radio" value="2"> 新視窗
                        </div>
                    </div>

                    </div>
                </div>
        </div>
    </div>
    <div class="text-center search_padding">
        <button type="submit" class="btn blue" id="btn_submit">確認送出</button>
        <button type="button" class="btn grey-mint" id="btn_return">返回列表</button>
    </div>
</form>

WebSiteProject/Areas/webadmin/Views/Destination_Index/Create.cshtml
@model WebSiteProject.Models.F_Destination_Type

@{
    ViewBag.Title = "Create";
}

<!--page bar start-->
<div class="page-bar all_width">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Index", "Home")">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            Destinations
            <i class="fa fa-circle"></i>
        </li>
        <li>目的地新增</li>
    </ul>
</div>
<!--page bar end-->

<div class="title_01">Destinations</div>

<div class="portlet light bordered">

    <form class="form-horizontal form-bordered" method="Post" id="editform" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        
        @Html.HiddenFor(Model => Model.Destination_Type_CreateDate)
        @Html.HiddenFor(Model => Model.Destination_Type_Link)
        <input id="hid_isAdd" type="hidden" name="isAdd" value='@ViewBag.IsAdd' />
        <div class="portlet light form-fit bordered">
            <div class="portlet-body form">
                <div class="form-horizontal form-bordered">
                    <div class="form-body" id="form-body">

                        <div class="form-group">
                            <div class="col-md-2 col-sm-2 col-xs-12 bg-grey_1 search_item">標題(上)</div>
                            <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                                @Html.TextBoxFor(model => model.Destination_Type_Title1,new {@class = "form-control input-medium" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-2 col-sm-2 col-xs-12 bg-grey_1 search_item">標題(下)</div>
                            <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                                <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                                    @Html.TextBoxFor(model => model.Destination_Type_Title2,new {@class = "form-control input-medium" })
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-2 col-sm-2 col-xs-12 search_item">圖片上傳</div>
                            <div class="col-md-10 col-sm-4 col-xs-12 bg-white mobile_white">
                                @Html.TextBoxFor(model => model.Destination_Type_ImgName, new { @id = "file_image", type = "file", @name = "uploadfile", accept = "image/*" })
                                @*<div id="div_oldfile" style="display:none">@Model.Destination_Type_ImgName<label style="color:blue;margin-left:10px;cursor:pointer" id="delimage">刪除</label></div>
                <input id="file_image" type="file" name="uploadfile" accept="image/*" />*@
                                @if (ViewBag.SType == "P")
                                {
                                    <span style="color:red;padding-left; font-size:12px">檔案類型jpg、png、gif，建議檔案大小2MB內，建議尺寸4000*850px</span>
                                }
                                else
                                {
                                    <span style="color:red;padding-left; font-size:12px">檔案類型jpg、png、gif，建議檔案大小2MB內，建議尺寸1200*2000px</span>
                                }

                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2 col-sm-2 col-xs-12 bg-grey_1 search_item">圖片說明</div>
                            <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                                <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                                    @Html.TextAreaFor(model => model.Destination_Type_ImgDescription, new { @style = "height:200px;width:700px;resize:none",@class = "form-control"  })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2 col-sm-2 col-xs-12 bg-grey_1 search_item">地點說明</div>
                            <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                                <div class="col-md-10 col-sm-10 col-xs-12 bg-white mobile_white">
                                    @Html.TextAreaFor(model => model.Destination_Type_Description, new { @style = "height:200px;width:700px;resize:none",@class = "form-control"  })
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="text-center search_padding">
            <button type="submit" class="btn blue" id="btn_submit">確認送出</button>
            <button type="button" class="btn grey-mint" id="btn_return">返回列表</button>
        </div>
    </form>

</div>

<script>
    $("#btn_return").click(function () {
        history.go(-1);
    });
           

</script>

WebSiteProject/Areas/webadmin/Views/Destination_Index/Faretemp.cshtml
@model IEnumerable<WebSiteProject.Models.Destination_Fare>

@{
    if (TempData["Msg"] != null)
    {
        <script>
            $(function () {
                var Msg = @Html.Raw(Json.Encode(TempData["Msg"]));
                alert(Msg);
            });
        </script>
    }
}

<style>
    hr {
        margin: 0px;
        border-top: 0px solid #eee;
    }

    .Five_Thingtodo_Header {
        background-color: lightgray;
        font-weight: bolder;
    }
</style>

<!--page bar start-->
<div class="page-bar all_width">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Index", "Home")">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            Destinations
            <i class="fa fa-circle"></i>
        </li>
        <li>費用設定</li>
    </ul>
</div>
<!--page bar end-->

<div class="title_01">Destinations</div>
<div id="Partial_Index_MenuLink">
    <!--.......-->
</div>

WebSiteProject/Areas/webadmin/Views/Destination_Index/MainTitleAndContent.cshtml
@model WebSiteProject.Models.Destination_Index

<!--page bar start-->
<div class="page-bar all_width">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Index", "Home")">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            Destinations
            <i class="fa fa-circle"></i>
        </li>
        <li>目的地主版設定</li>
    </ul>
</div>
<!--page bar end-->

<div class="title_01">Destinations目的地主版</div>
<div id="Partial_Index_MenuLink">
    <div class="portlet light bordered">
        <!--set item start-->
        <div class="table-toolbar">
            <div class="col-md-6 col-sm-12 col-xs-12">
                <p class="class_title">管理項目</p>
                <div class="display_inline">
                    <select id="Index_Partial_Select" class="form-control checkitem" onchange="window.location.href=this.value">
                        @*<option data-index="0" value="#">請選擇</option>*@
                        <option data-index="1" value="@Url.Action("Index", "AD", new { type = "main" , stype = "P", site_id = 3, MenuType=179})">輪播牆設定</option>
                        <option data-index="2" value="@Url.Action("MainTitleAndContent", "Destination_Index")" selected>目的地主版設定(標題&文字)</option>
                        <option data-index="3" value="@Url.Action("Destination","Destination_Index", new { F_MenuType = 179,MenuType=179})">目的地設定</option>
                        <option data-index="4" value="@Url.Action("Index","Destination_MapLegend", new { F_MenuType = 179,MenuType=179})">MapLegend設定</option>
                        <option data-index="5" value="@Url.Action("ModelItem", "Message",new { mainid = '9' })">旅遊資訊文章設定</option>
                    </select>
                </div>
            </div>
        </div>


        <div class="title_04" style="display:none">目的地主版設定(標題&文字)</div>

        <div class="form-horizontal form-bordered" id="editform" enctype="multipart/form-data">

            <form method="post" action="@Url.Action("MainTitleAndContent_Edit", "Destination_Index")">
                <div class="portlet light form-fit bordered">
                    <div class="portlet-body form">
                        <div class="form-horizontal form-bordered">
                            <div class="form-body">
                                <input name="_Destination_Index_ID" type="hidden" value="@Model.Destination_ID" />
                                <div class="form-group">
                                    <div class="col-md-3 col-sm-12 col-xs-12 search_item text-center">
                                        <span>標題名稱</span>
                                    </div>
                                    <div class="col-md-9 col-sm-12 col-xs-12 bg-white mobile_white ">
                                        <textarea id="_Destination_Index_Title" name="_Destination_Index_Title" class="form-control" style="height:50px;resize:none">@Model.Destination_Title</textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-3 col-sm-12 col-xs-12 search_item text-center">
                                        <span>內容</span>
                                    </div>
                                    <div class="col-md-9 col-sm-12 col-xs-12 bg-white mobile_white ">
                                        <textarea id="_Destination_Index_Context" name="_Destination_Index_Context" class="form-control f_textarea" style="height:250px;resize:none">@Model.Destination_Context</textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-5 col-sm-12 col-xs-12 bg-white mobile_white text-center">

                                    </div>
                                    <div class="col-md-1 col-sm-12 col-xs-12 bg-white mobile_white text-center">
                                        <button name="Btn_Destination_Index_Edit" class="form-control btn blue text-center" data-id="@Model.Destination_ID" data-name="@Model.Destination_Title">確認送出</button>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>

</div>


@section scripts{
    <script>
        $(function () {
            
            //Content加入換行符號
            addbr();

            //Title加入換行符號
            addbr1()


        });


        //插入換行符號
        function addbr() {
            $("#addbr").click(function () {
                console.log("</br>");
                str = "</br>";
                insertText(_Thingtodo_Index_Content, str)
            });
        };

        //插入換行符號
        function addbr1() {
            $("#addbr1").click(function () {
                console.log("</br>");
                str = "</br>";
                insertText(_Thingtodo_Index_Title, str)
            });
        };

        //取得當前游標位置
        //obj是textarea的id，str是要加入的字串
        //ex: <textarea id="test"></textarea>; str="<br/>"; insertText(test, str)
        function insertText(obj, str) {
            if (document.selection) {
                var sel = document.selection.createRange();
                sel.text = str;
            } else if (typeof obj.selectionStart === 'number' && typeof obj.selectionEnd === 'number') {
                var startPos = obj.selectionStart,
                    endPos = obj.selectionEnd,
                    cursorPos = startPos,
                    tmpStr = obj.value;
                obj.value = tmpStr.substring(0, startPos) + str + tmpStr.substring(endPos, tmpStr.length);
                cursorPos = str.length;
                obj.selectionStart = obj.selectionEnd = cursorPos;
            } else {
                obj.value = str;
            }
        }



    </script>
}