WebSiteProject/Areas/webadmin/Controllers/PatentController.cs
using Services.Interface;
using Services.Manager;
using SQLModel;
using SQLModel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModels;
using Utilities;
using System.Configuration;
using System.IO;
using WebSiteProject.Code;

namespace WebSiteProject.Areas.webadmin.Controllers
{

    public class PatentController : AppController
    {
        IModelPatentManager _IModelPatentManager;
        public PatentController()
        {
            _IModelPatentManager = serviceinstance.ModelPatentManager;
        }
        [AuthoridUrl("Model/Index", "")]
        public ActionResult Index()
        {
            CheckAuth(System.Reflection.MethodBase.GetCurrentMethod());
            ViewBag.Title = "專利管理";
            Session["IsFromClick"] = "Y";
            return View();
        }

        //====Main
        #region EditUnit
        public ActionResult EditUnit(string mainid, string name)
        {
            if (Request.IsAuthenticated)
            {
                var str = "";
                if (mainid == "-1")
                {
                    Common.SetLogs(this.UserID, this.Account, "新增專利管理管理單元名稱=" + name);
                    var newid = 0;
                    str = _IModelPatentManager.AddUnit(name, this.LanguageID, this.Account, ref newid);
                }
                else
                {
                    Common.SetLogs(this.UserID, this.Account, "修改專利管理單元名稱 ID=" + mainid + " 改為:" + name);
                    str = _IModelPatentManager.UpdateUnit(name, mainid, this.Account);
                }
                return Json(str);
            }
            else { return Json("請先登入"); }
        }
        #endregion

        #region PagingMain
        public ActionResult PagingMain(SearchModelBase model)
        {
            model.LangId = this.LanguageID;
            return Json(_IModelPatentManager.Paging(model));
        }
        #endregion

        #region EditSeq
        public ActionResult EditSeq(int? id, int seq, string type)
        {
            if (Request.IsAuthenticated)
            {
                Common.SetLogs(this.UserID, this.Account, "變更專利管理單元管理排序 ID=" + id + "排序=" + seq);
                return Json(_IModelPatentManager.UpdateSeq(id.Value, seq, this.LanguageID, this.Account, this.UserName));
            }
            else { return Json("請先登入"); }
        }
        #endregion

        #region SetMainDelete
        public ActionResult SetMainDelete(string[] idlist, string delaccount)
        {
            if (Request.IsAuthenticated)
            {
                Common.SetLogs(this.UserID, this.Account, "刪除下列專利管理=" + delaccount);
                return Json(_IModelPatentManager.Delete(idlist, delaccount, this.LanguageID, this.Account, this.UserName));
            }
            else { return Json("請先登入"); }
        }
        #endregion

        //===============
        #region ModelItem
        [AuthoridUrl("Model/Index", "")]
        public ActionResult ModelItem(string mainid)
        {
            if (mainid.IsNullorEmpty()) { return RedirectToAction("Index"); }
            CheckAuth(System.Reflection.MethodBase.GetCurrentMethod());
            if (Session["IsFromClick"] != null)
            {
                ViewBag.IsFromClick = "Y";
            }
            var grouplist = _IModelPatentManager.GetAllGroupSelectList(mainid);
            grouplist.Insert(0, new System.Web.Mvc.SelectListItem() { Text = "全部", Value = "" });
            ViewBag.grouplist = grouplist;
            ViewBag.mainid = mainid.AntiXssEncode();
            var maindata = _IModelPatentManager.Where(new  ModelPatentMain()
            {
                ID = int.Parse(mainid)
            });
            if (maindata.Count() > 0) { ViewBag.Title = maindata.First().Name; }
            return View();
        }
        #endregion

        //=====Group
        #region GroupEdit
        [AuthoridUrl("Model/Index", "")]
        public ActionResult GroupEdit(string mainid)
        {
            CheckAuth(System.Reflection.MethodBase.GetCurrentMethod());
            ViewBag.mainid = mainid.AntiXssEncode();
            return View();
        }
        #endregion

        #region PagingGroup
        public ActionResult PagingGroup(SearchModelBase model)
        {
            return Json(_IModelPatentManager.PagingGroup(model));
        }
        #endregion

        #region EditGroupSeq
        public ActionResult EditGroupSeq(int? id, int seq, string mainid)
        {
            if (Request.IsAuthenticated)
            {
                Common.SetLogs(this.UserID, this.Account, "變更專利管理排序MainID=" + mainid + " ID =" + id + "排序=" + seq);
                return Json(_IModelPatentManager.UpdateGroupSeq(id.Value, seq, mainid, this.Account, this.UserName));
            }
            else { return Json("請先登入"); }
        }
        #endregion

        #region SetGroupDelete
        public ActionResult SetGroupDelete(string[] idlist, string delaccount, string type)
        {
            if (Request.IsAuthenticated)
            {
                Common.SetLogs(this.UserID, this.Account, "刪除專利管理=" + delaccount);
                return Json(_IModelPatentManager.DeleteGroup(idlist, delaccount, this.Account, this.UserName));
            }
            else { return Json("請先登入"); }

        }
        #endregion

        #region SetGroupStatus
        public ActionResult SetGroupStatus(string id, bool status, string account, string username)
        {
            if (Request.IsAuthenticated)
            {
                Common.SetLogs(this.UserID, this.Account, "設定專利管理d=" + id + "為" + status);
                return Json(_IModelPatentManager.UpdateGroupStatus(id, status, this.Account, this.UserName));
            }
            else { return Json("請先登入"); }

        }
        #endregion

        #region EditGroup
        public ActionResult EditGroup(string name, string id, string mainid)
        {
            if (id == "-1" || id.IsNullorEmpty())
            {
                Common.SetLogs(this.UserID, this.Account, "新增專利管理名稱=" + name + " mainid=" + mainid);
                return Json(_IModelPatentManager.EditGroup(name, id, mainid, this.Account));
            }
            else
            {
                Common.SetLogs(this.UserID, this.Account, "修改專利管理名稱=" + name + " id=" + id);
                return Json(_IModelPatentManager.EditGroup(name, id, mainid, this.Account));
            }

        }
        #endregion

        //===============

        #region PatentEdit
        [AuthoridUrl("Model/Index", "")]
        public ActionResult PatentEdit(string mainid, string itemid="-1")
        {
            if (mainid.IsNullorEmpty()) { return RedirectToAction("Index"); }
            var isview = Request.Form["isview"] == null ? "" : Request.Form["isview"];
            ViewBag.isview = isview.AntiXssEncode();
            if (isview == null || isview == "")
            {
                CheckAuth(System.Reflection.MethodBase.GetCurrentMethod());
            }
            ViewBag.grouplist = _IModelPatentManager.GetAllGroupSelectList(mainid);
            PatentEditModel model = null;
            model = _IModelPatentManager.GetModelByID(mainid, itemid);
            return View(model);
        }
        #endregion

        #region PagingItem
        public ActionResult PagingItem(PatentSearchModel model)
        {
            return Json(_IModelPatentManager.PagingItem(model.ModelID.ToString(), model));
        }
        #endregion

        #region UpdateItemSeq
        public ActionResult UpdateItemSeq(int modelid, int id, int seq, string type)
        {
            if (Request.IsAuthenticated)
            {
                Common.SetLogs(this.UserID, this.Account, "修改專利管理排序ID=" + id + " sequence=" + seq);
                return Json(_IModelPatentManager.UpdateItemSeq(modelid, id, seq, this.Account, this.UserName));
            }
            else { return Json("請先登入"); }
        }
        #endregion

        #region SetItemStatus
        public ActionResult SetItemStatus(string id, bool status, string type)
        {
            if (Request.IsAuthenticated)
            {
                Common.SetLogs(this.UserID, this.Account, "修改專利管理狀態ID=" + id + " status=" + status);
                return Json(_IModelPatentManager.SetItemStatus(id, status, this.Account, this.UserName));
            }
            else { return Json("請先登入"); }
        }
        #endregion

        #region SetItemDelete
        public ActionResult SetItemDelete(string[] idlist, string delaccount, string type)
        {
            if (Request.IsAuthenticated)
            {
                Common.SetLogs(this.UserID, this.Account, "刪除部落客文章管理=" + delaccount);
                return Json(_IModelPatentManager.DeleteItem(idlist, delaccount, this.Account, this.UserName));
            }
            else { return Json("請先登入"); }

        }
        #endregion

        #region AddSelItem
        public ActionResult AddSelItem(int Index)
        {
            ViewBag.index = Request.Form["index"] == null ? "0" : Request.Form["index"];
            ViewBag.seqindex = int.Parse(ViewBag.index) + 1;
            return PartialView();
        }
        #endregion

        #region SaveItem
        public ActionResult SaveItem(PatentEditModel model)
        {
            if (model.UploadFile != null)
            {
                model.UploadFileName = model.UploadFile.FileName.Split('\\').Last();
                var uploadfilepath = ConfigurationManager.AppSettings["UploadFile"];
                if (uploadfilepath.IsNullorEmpty())
                {
                    uploadfilepath = Request.PhysicalApplicationPath + "\\UploadFile";
                }
                var newpath = uploadfilepath + "\\PatentItem\\";
                if (System.IO.Directory.Exists(newpath) == false)
                {
                    System.IO.Directory.CreateDirectory(newpath);
                }

WebSiteProject/Areas/webadmin/Views/Patent/AddSelItem.cshtml
<tr id="tr_@(ViewBag.index)" class="selitem" seqidx="@(ViewBag.seqindex)">
    <td class="text-center">
        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
            <input type="checkbox" class="checkboxes">
            <span name="check_@(ViewBag.index)"></span>
        </label>
    </td>
    <td><input type="text" class="form-control Nation" value="" /></td>
    <td><input type="text" class="form-control Patentno" value="" /></td>
    <td><input type="text" class="form-control PatentDate" value=""  maxlength="10" id="PatentDate@(ViewBag.seqindex)"/></td>
    <td><input type="text" class="form-control EarlyPublicDate" value="" maxlength="10"  id="EarlyPublicDate@(ViewBag.seqindex)"/></td>
    <td><input type="text" class="form-control EarlyPublicNo" value="" /></td>
    <td><input type="text" class="form-control Deadline" value="" maxlength="10" id="Deadline@(ViewBag.seqindex)"/></td>
</tr>
<script>

    $('#PatentDate@(ViewBag.seqindex)').datepicker({
        format: "yyyy/mm/dd",
        autoclose: true,
        language: 'zh-TW'
    });
    $('#EarlyPublicDate@(ViewBag.seqindex)').datepicker({
        format: "yyyy/mm/dd",
        autoclose: true,
        language: 'zh-TW'
    });
    $('#Deadline@(ViewBag.seqindex)').datepicker({
        format: "yyyy/mm/dd",
        autoclose: true,
        language: 'zh-TW'
    });
</script>

WebSiteProject/Areas/webadmin/Views/Patent/GroupEdit.cshtml
@model SearchModelBase
<script src="@Url.Content("~/Scripts/datatable.js")"></script>
<script src="@Url.Content("~/Scripts/custom.js")"></script>
<script src="@Url.Content("~/Scripts/bootbox.min.js")"></script>
<!--page bar start-->
<div class="page-bar all_width">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Index","Home")">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","Model")">模組管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","Patent")">專利管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("ModelItem","Patent",new { mainid= ViewBag.mainid })">清單</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            類別管理
        </li>
    </ul>
</div>
<!--page bar end-->
<div class="title_01"> 類別管理設定</div>
<div class="portlet light bordered">
    <!--set item start-->
    <div class="table-toolbar">
        <div class="col-md-6 col-sm-12 col-xs-12 mobile_left ">
        </div>
        <div class="col-md-6 col-sm-12 col-xs-12 mobile_left ">
            <p class="display_inline ">
                <button class="btn green-meadow" id='btn_add'>新增 <i class="fa fa-plus"></i></button>
                <button type="button" class="btn grey-mint" id="btn_return" onclick="document.location.href='@Url.Action("ModelItem")?mainid=@ViewBag.mainid'">返回</button>
            </p>
        </div>
    </div>
    <!--set item end-->
    <!--table start-->
    <div class="table-scrollable">
        <table class="table table-bordered table-hover" border="0" cellspacing="0" cellpadding="0" style="width:500px"
               id="eventtable"
               data-url="@Url.Action("PagingGroup")"
               data-sort-name='Sort'
               data-page-size='10'
               data-filed-id='ID'
               data-max-pagination='10'>
            <thead>
                <tr class="bg-grey_1" filed-class='odd gradeX'>
                    <th width="80px" class="text-center"  filed-type='delcheckbox'>
                         <label class='mt-checkbox mt-checkbox-single mt-checkbox-outline'>
                          <input type='checkbox' class='checkboxes' id="chk_all" /><span></span>
                          </label><button class="btn red-mint btn-xs" id='btn_del'><i class="glyphicon glyphicon-trash"></i></button>
                    </th>
                    <th filed-name='Sort' width="160px" class="text-center"  filed-type='numbertextcheck' filed-item-class="sortedit">排序</th>
                    <th filed-name='Group_Name' class="text-center"  filed-type='link'>類別名稱</th>
                    <th width="80px" filed-name='Enabled'  class="text-center" filed-type='checkbox'   filed-item-class="chkstatus">顯示</th>
                </tr>
            </thead><tbody></tbody>
        </table>
    </div>
    <div id="page_number" class="table-toolbar">
        <div class="col-md-4 col-sm-12 col-xs-12 page_total" id="tableinfo"></div>
        <div class="col-md-8 col-sm-12 col-xs-12 page_icon">
            <div class="btn-group" id="pagination">
            </div>
        </div>
    </div>
    <!--table end-->

</div>
<!--message end-->
@section scripts {
    <script>
        var selvalue = [];
        $(document).ready(function () {
            mytable = $("#eventtable").myDataTable().TableList[0];
            mytable.settingTdData = myDataTableTr;
            mytable.settingTableInfo = function (tableinfoId, totalcnt, offsetcnt, nowpagecnt) {
                var totalclick = mytable.keepcheckid.length;
                $("#" + tableinfoId).html('總筆數:' + totalcnt + '，顯示' + (totalcnt <= 0 ? 0 : offsetcnt) + "~" + (offsetcnt + nowpagecnt - 1) );
            };
            mytable.SearchModelBase.ModelID= '@ViewBag.mainid';
            mytable.GetData(1);
            var obj = {};
            obj.item = "類別";
            obj.mainid = '@ViewBag.mainid';
            RegisterOrder("#eventtable", ".sortedit", '@Url.Action("EditGroupSeq")', obj);
            RegisterClickAll("#chk_all", '#eventtable tbody .chksel', "#selvalue");
            RegisterDelete("#btn_del", '#eventtable .chksel:checked', '@Url.Action("SetGroupDelete")', obj);
            RegisterClicklink("#eventtable", ".edit", '@Url.Action("EditGroup")', obj, 'UpdateItem');
            RegisterClicklink("#eventtable", ".manage", '@Url.Action("ModelItem")', obj);
            RegisterClick("#eventtable", ".chkstatus", '@Url.Action("SetGroupStatus")', obj);
            $("#btn_add").click(function () { CallAddDialog('@Url.Action("EditGroup")', obj); });
       });
    </script>
}

WebSiteProject/Areas/webadmin/Views/Patent/ModelItem.cshtml
@model PatentSearchModel
<script src="@Url.Content("~/Scripts/datatable.js")"></script>
<script src="@Url.Content("~/Scripts/custom.js")"></script>
<script src="@Url.Content("~/Scripts/components-date-time-pickers.min.js")"></script>
<script src="@Url.Content("~/Scripts/bootstrap-datepicker.min.js")"></script>
<script src="@Url.Content("~/Scripts/bootbox.min.js")"></script>
<!--page bar start-->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Index","Home")">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","Model")">模組管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","Patent")">專利管理</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            清單
        </li>
    </ul>
</div>
<!--page bar end-->
<div class="title_01">@ViewBag.Title</div>
<div class="portlet light bordered">
        <!--management item start-->
    <div class="table-toolbar">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="display_inline">
                <p class="class_title">管理項目</p>
                <select class="form-control_1" id="sel_unit" onChange="window.location.href=this.value">
                    <option value="#" selected>專利管理</option>
                    <option value="@Url.Action("UnitSetting", new { mainid = ViewBag.mainid })">單元設定</option>
                </select>
            </div>
        </div>
    </div>
    <hr>
    <!--management item end-->
    <!--set item start-->
    <div class="table-toolbar">
        <div class="col-md-6 col-sm-12 col-xs-12">
            <div class="display_inline">
                <p class="class_title">類別</p>
                @{var grouplist = (IList<SelectListItem>)ViewBag.grouplist;
                    <select class="form-control_1" id="GroupId">
                        @foreach (var g in grouplist) {<option value="@g.Value">@g.Text</option>}</select>}
                <p class="display_inline"><a href="#" class="btn grey-mint" role="button" id="btn_groupmanager">管理</a></p>
            </div>
        </div>
        <div class="col-md-6 col-sm-12 col-xs-12 mobile_left">
            <p class="display_inline">
                <button class="btn blue search_icon">搜尋 <i class="fa fa-search"></i></button>
                <button class="btn green-meadow" id='btn_add'>新增 <i class="fa fa-plus"></i></button>
                <button type="button" class="btn grey-mint" id="btn_return" onclick="document.location.href='@Url.Action("Index")'">返回</button>
            </p>
        </div>
    </div>
    <!--set item end-->
    <!--search item start-->
    <div class="search_menu" style="display: none" id="searchForm">
        <div class="portlet light form-fit bordered" id="searchForm">
            <div class="portlet-body form">
                <form class="form-horizontal form-bordered">
                    <div class="form-body" id="searchForm">
                        <div class="form-group bg-grey_1">
                            <div class="col-md-2 search_item">類別</div>
                            <div class="col-md-10 bg-white">
                                @Html.DropDownList(@Html.IdFor(m => m.GroupId).ToString() + '2', (IEnumerable<SelectListItem>)ViewBag.grouplist, new { @class = "form_02" })
                            </div>
                        </div>
                        <div class="form-group bg-grey_1">
                            <div class="col-md-2 search_item">發佈日期</div>
                            <div class="col-md-10 bg-white">
                                <div class="input-group input-large">
                                    <div class="date-picker input-daterange" data-date-format="yyyy/mm/dd">
                                        @Html.EditorFor(model => model.PublicshDateFrom, new { htmlAttributes = new { @class = "form-control", placeholder = "開始日期" } })
                                    </div>
                                    <span class="input-group-addon"> to </span>
                                    <div class="date-picker input-daterange" data-date-format="yyyy/mm/dd">
                                        @Html.EditorFor(model => model.PublicshDateTo, new { htmlAttributes = new { @class = "form-control", placeholder = "結束日期" } })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group bg-grey_1">
                            <div class="col-md-2 search_item">顯示日期</div>
                            <div class="col-md-10 bg-white">
                                <div class="input-group input-large">
                                    <div class="date-picker input-daterange" data-date-format="yyyy/mm/dd">
                                        @Html.EditorFor(model => model.DisplayFrom, new { htmlAttributes = new { @class = "form-control", placeholder = "開始日期" } })
                                    </div>
                                    <span class="input-group-addon"> to </span>
                                    <div class="date-picker input-daterange" data-date-format="yyyy/mm/dd">
                                        @Html.EditorFor(model => model.DisplayTo, new { htmlAttributes = new { @class = "form-control", placeholder = "結束日期" } })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group bg-grey_1">
                            <div class="col-md-2 search_item">標題/內容</div>
                            <div class="col-md-10 bg-white">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2 search_item_1">是否在顯示區間</div>
                            <div class="col-md-4 bg-white">
                                <select class="form-control input-small" id='IsRange'>
                                    <option value="" selected>全部</option>
                                    <option value="1">是</option>
                                    <option value="0">否</option>
                                </select>
                            </div>
                            <div class="col-md-2 search_item_1">上架</div>
                            <div class="col-md-4 bg-white">
                                <select class="form-control input-small" id='Enabled'>
                                    <option value="" selected>全部</option>
                                    <option value="1">顯示</option>
                                    <option value="0">隱藏</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="text-center search_padding">
            <button type="button" class="btn blue" id="btn_search">搜尋 <i class="fa fa-search"></i></button>
            <button type="button" class="btn blue-hoki" id="btn_searchrefresh">清除搜尋<i class="fa fa-refresh"></i></button>
        </div>
    </div>
    <!--search item end-->
    <!--table start-->
    <div class="table-scrollable">
        <table class="table table-bordered table-hover" border="0" cellspacing="0" cellpadding="0"
               id="eventtable"
               data-url="@Url.Action("PagingItem")"
               data-sort-name='Sort'
               data-page-size='10'
               data-filed-id='ItemID'
               data-max-pagination='10'>
            <thead>
                <tr class="bg-grey_1" filed-class='odd gradeX'>
                    <th width="80" class="text-center delete_th" filed-type='delcheckbox'>
                        <label class='mt-checkbox mt-checkbox-single mt-checkbox-outline'>
                            <input type='checkbox' class='checkboxes' id="chk_all" /><span></span>
                        </label>
                        <button class="btn red-mint btn-xs" id='btn_del'><i class="glyphicon glyphicon-trash"></i></button>
                    </th>
                    <th filed-name='Sort' width="160px" class="text-center" filed-type='numbertextcheck' filed-item-class="sortedit">排序</th>
                    <th filed-name='PublicshDate' width="100px" class="text-center">發佈日期</th>
                    <th filed-name='Title' class="text-center" filed-type='link'>標題</th>
                    <th filed-name='GroupName' width="150px" class="text-center" filed-item-class='text-center'>類別名稱</th>
                    <th filed-name='VerifyStr' width="50px" class="text-center" filed-item-class='text-center'>審核狀態</th>
                    <th filed-name='IsRange' width="80px" class="text-center" filed-item-class='text-center'>是否在顯示區間</th>
                    <th filed-name='Enabled' width="80px" class="text-center" filed-type='checkbox' filed-item-class="checkboxes chkstatus">上架</th>

                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

    <div id="page_number" class="table-toolbar">
        <div class="col-md-4 col-sm-12 col-xs-12 page_total" id="tableinfo"></div>
        <div class="col-md-8 col-sm-12 col-xs-12 page_icon">
            <div class="btn-group" id="pagination">
            </div>
        </div>
    </div>
    <!--table end-->

</div>

<!--message end-->
@section scripts {
    <script>

        $(document).ready(function () {
            $("#btn_return").hide();
            if ('@ViewBag.IsFromClick' == 'Y') {
                $("#btn_return").show();
            }
            var mainid ='@ViewBag.mainid'
            RegisterSearchItem();
            $("#btn_searchrefresh").click(function () {
                $("#searchForm :input").val('');
                mytable.GetData();
            });
            mytable = $("#eventtable").myDataTable().TableList[0];
            mytable.settingTdData = myDataTableTr;
            mytable.settingTableInfo = function (tableinfoId, totalcnt, offsetcnt, nowpagecnt) {
                var totalclick = mytable.keepcheckid.length;
                $("#" + tableinfoId).html('總筆數:' + totalcnt + '，顯示' + (totalcnt <= 0 ? 0 : offsetcnt) + "~" + (offsetcnt + nowpagecnt - 1));
            };
            mytable.SearchModelBase.ModelID = mainid;
            mytable.GetData(1);
            var obj = {};
            obj.modelid = mainid;
             $("#btn_search").click(function () {
                var SearchModelBase = mytable.SearchModelBase;
                SearchModelBase.DisplayFrom = $('#@Html.IdFor(m => m.DisplayFrom)').val();
                SearchModelBase.DisplayTo = $('#@Html.IdFor(m => m.DisplayTo)').val();
                SearchModelBase.PublicshDateFrom = $('#@Html.IdFor(m => m.PublicshDateFrom)').val();
                SearchModelBase.PublicshDateTo = $('#@Html.IdFor(m => m.PublicshDateTo)').val();
                SearchModelBase.Enabled = $('#@Html.IdFor(m => m.Enabled)' ).val();
                SearchModelBase.Title = $('#@Html.IdFor(m => m.Title)').val();
                 SearchModelBase.GroupId = $('#@Html.IdFor(m => m.GroupId)' + '2').val();
                        SearchModelBase.IsRange = $('#@Html.IdFor(m => m.IsRange)').val();
                SearchModelBase.Search = "Y";
                mytable.GetData();
            });
             $("#GroupId").change(function () {
                 $("#searchForm :input").val('');
                 var SearchModelBase = mytable.SearchModelBase;
                 SearchModelBase.GroupId = $('#GroupId').val();
                 SearchModelBase.Search = "Y";
                 mytable.GetData();
             });
            RegisterOrder("#eventtable", ".sortedit", '@Url.Action("UpdateItemSeq")', obj);
            RegisterClickAll("#chk_all", '#eventtable tbody .chksel', "#selvalue");
            RegisterDelete("#btn_del", '#eventtable .chksel:checked', '@Url.Action("SetItemDelete")', {keyindex:"3"});
            RegisterClicklink("#eventtable", ".edit", '@Url.Action("PatentEdit")', { idkey: "itemid", mainid: mainid},"itemid");
            RegisterClick("#eventtable", ".chkstatus", '@Url.Action("SetItemStatus")', obj);
            $("#btn_groupmanager").click(function () {
                    var obj = {};
                    obj.mainid = mainid;
                    CreatePost('@Url.Action("GroupEdit")', obj);
            });
            $("#btn_add").click(function () {
               var obj = {};
               obj.mainid = mainid;
                CreatePost('@Url.Action("PatentEdit")', obj);
            });
        });
    </script>
}